// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: aether.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - aether.AetherOrchestrator

/// Namespace containing generated types for the "aether.AetherOrchestrator" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Aether_AetherOrchestrator: Sendable {
    /// Service descriptor for the "aether.AetherOrchestrator" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Namespace for "ScanLibrary" metadata.
        internal enum ScanLibrary: Sendable {
            /// Request type for "ScanLibrary".
            internal typealias Input = Aether_ScanRequest
            /// Response type for "ScanLibrary".
            internal typealias Output = Aether_ScanProgress
            /// Descriptor for "ScanLibrary".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "ScanLibrary"
            )
        }
        /// Namespace for "GetLibrary" metadata.
        internal enum GetLibrary: Sendable {
            /// Request type for "GetLibrary".
            internal typealias Input = Aether_Empty
            /// Response type for "GetLibrary".
            internal typealias Output = Aether_Game
            /// Descriptor for "GetLibrary".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "GetLibrary"
            )
        }
        /// Namespace for "LaunchGame" metadata.
        internal enum LaunchGame: Sendable {
            /// Request type for "LaunchGame".
            internal typealias Input = Aether_LaunchRequest
            /// Response type for "LaunchGame".
            internal typealias Output = Aether_LaunchResponse
            /// Descriptor for "LaunchGame".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "LaunchGame"
            )
        }
        /// Namespace for "StopGame" metadata.
        internal enum StopGame: Sendable {
            /// Request type for "StopGame".
            internal typealias Input = Aether_GameId
            /// Response type for "StopGame".
            internal typealias Output = Aether_OperationStatus
            /// Descriptor for "StopGame".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "StopGame"
            )
        }
        /// Namespace for "SubscribeToGameState" metadata.
        internal enum SubscribeToGameState: Sendable {
            /// Request type for "SubscribeToGameState".
            internal typealias Input = Aether_Empty
            /// Response type for "SubscribeToGameState".
            internal typealias Output = Aether_GameStateUpdate
            /// Descriptor for "SubscribeToGameState".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "SubscribeToGameState"
            )
        }
        /// Namespace for "GetGameDetailWidgets" metadata.
        internal enum GetGameDetailWidgets: Sendable {
            /// Request type for "GetGameDetailWidgets".
            internal typealias Input = Aether_GameId
            /// Response type for "GetGameDetailWidgets".
            internal typealias Output = Aether_WidgetList
            /// Descriptor for "GetGameDetailWidgets".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "GetGameDetailWidgets"
            )
        }
        /// Namespace for "TriggerPluginAction" metadata.
        internal enum TriggerPluginAction: Sendable {
            /// Request type for "TriggerPluginAction".
            internal typealias Input = Aether_PluginAction
            /// Response type for "TriggerPluginAction".
            internal typealias Output = Aether_OperationStatus
            /// Descriptor for "TriggerPluginAction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "TriggerPluginAction"
            )
        }
        /// Namespace for "GetPlugins" metadata.
        internal enum GetPlugins: Sendable {
            /// Request type for "GetPlugins".
            internal typealias Input = Aether_Empty
            /// Response type for "GetPlugins".
            internal typealias Output = Aether_PluginList
            /// Descriptor for "GetPlugins".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "GetPlugins"
            )
        }
        /// Namespace for "GetSetupWidgets" metadata.
        internal enum GetSetupWidgets: Sendable {
            /// Request type for "GetSetupWidgets".
            internal typealias Input = Aether_PluginName
            /// Response type for "GetSetupWidgets".
            internal typealias Output = Aether_WidgetList
            /// Descriptor for "GetSetupWidgets".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator"),
                method: "GetSetupWidgets"
            )
        }
        /// Descriptors for all methods in the "aether.AetherOrchestrator" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            ScanLibrary.descriptor,
            GetLibrary.descriptor,
            LaunchGame.descriptor,
            StopGame.descriptor,
            SubscribeToGameState.descriptor,
            GetGameDetailWidgets.descriptor,
            TriggerPluginAction.descriptor,
            GetPlugins.descriptor,
            GetSetupWidgets.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "aether.AetherOrchestrator" service.
    internal static let aether_AetherOrchestrator = GRPCCore.ServiceDescriptor(fullyQualifiedService: "aether.AetherOrchestrator")
}

// MARK: aether.AetherOrchestrator (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator {
    /// Streaming variant of the service protocol for the "aether.AetherOrchestrator" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ScanLibrary" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LIBRARY: Getting games into the UI
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_ScanRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_ScanProgress` messages.
        func scanLibrary(
            request: GRPCCore.StreamingServerRequest<Aether_ScanRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_ScanProgress>

        /// Handle the "GetLibrary" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_Game` messages.
        func getLibrary(
            request: GRPCCore.StreamingServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_Game>

        /// Handle the "LaunchGame" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LAUNCHING: The core function
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_LaunchRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_LaunchResponse` messages.
        func launchGame(
            request: GRPCCore.StreamingServerRequest<Aether_LaunchRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_LaunchResponse>

        /// Handle the "StopGame" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_GameId` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_OperationStatus` messages.
        func stopGame(
            request: GRPCCore.StreamingServerRequest<Aether_GameId>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_OperationStatus>

        /// Handle the "SubscribeToGameState" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_GameStateUpdate` messages.
        func subscribeToGameState(
            request: GRPCCore.StreamingServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_GameStateUpdate>

        /// Handle the "GetGameDetailWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PLUGINS: The interactive layer
        /// > Frontend asks: "What widgets should I show for this game?"
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_GameId` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_WidgetList` messages.
        func getGameDetailWidgets(
            request: GRPCCore.StreamingServerRequest<Aether_GameId>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_WidgetList>

        /// Handle the "TriggerPluginAction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Frontend says: "User clicked the button in the plugin widget"
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_PluginAction` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_OperationStatus` messages.
        func triggerPluginAction(
            request: GRPCCore.StreamingServerRequest<Aether_PluginAction>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_OperationStatus>

        /// Handle the "GetPlugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of loaded plugins
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_PluginList` messages.
        func getPlugins(
            request: GRPCCore.StreamingServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_PluginList>

        /// Handle the "GetSetupWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Aether_PluginName` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_WidgetList` messages.
        func getSetupWidgets(
            request: GRPCCore.StreamingServerRequest<Aether_PluginName>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_WidgetList>
    }

    /// Service protocol for the "aether.AetherOrchestrator" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Aether_AetherOrchestrator.StreamingServiceProtocol {
        /// Handle the "ScanLibrary" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LIBRARY: Getting games into the UI
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_ScanRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_ScanProgress` messages.
        func scanLibrary(
            request: GRPCCore.ServerRequest<Aether_ScanRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_ScanProgress>

        /// Handle the "GetLibrary" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_Game` messages.
        func getLibrary(
            request: GRPCCore.ServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_Game>

        /// Handle the "LaunchGame" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LAUNCHING: The core function
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_LaunchRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_LaunchResponse` message.
        func launchGame(
            request: GRPCCore.ServerRequest<Aether_LaunchRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_LaunchResponse>

        /// Handle the "StopGame" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_OperationStatus` message.
        func stopGame(
            request: GRPCCore.ServerRequest<Aether_GameId>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_OperationStatus>

        /// Handle the "SubscribeToGameState" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Aether_GameStateUpdate` messages.
        func subscribeToGameState(
            request: GRPCCore.ServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Aether_GameStateUpdate>

        /// Handle the "GetGameDetailWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PLUGINS: The interactive layer
        /// > Frontend asks: "What widgets should I show for this game?"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_WidgetList` message.
        func getGameDetailWidgets(
            request: GRPCCore.ServerRequest<Aether_GameId>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_WidgetList>

        /// Handle the "TriggerPluginAction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Frontend says: "User clicked the button in the plugin widget"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginAction` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_OperationStatus` message.
        func triggerPluginAction(
            request: GRPCCore.ServerRequest<Aether_PluginAction>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_OperationStatus>

        /// Handle the "GetPlugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of loaded plugins
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_PluginList` message.
        func getPlugins(
            request: GRPCCore.ServerRequest<Aether_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_PluginList>

        /// Handle the "GetSetupWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginName` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Aether_WidgetList` message.
        func getSetupWidgets(
            request: GRPCCore.ServerRequest<Aether_PluginName>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Aether_WidgetList>
    }

    /// Simple service protocol for the "aether.AetherOrchestrator" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Aether_AetherOrchestrator.ServiceProtocol {
        /// Handle the "ScanLibrary" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LIBRARY: Getting games into the UI
        ///
        /// - Parameters:
        ///   - request: A `Aether_ScanRequest` message.
        ///   - response: A response stream of `Aether_ScanProgress` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func scanLibrary(
            request: Aether_ScanRequest,
            response: GRPCCore.RPCWriter<Aether_ScanProgress>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "GetLibrary" method.
        ///
        /// - Parameters:
        ///   - request: A `Aether_Empty` message.
        ///   - response: A response stream of `Aether_Game` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func getLibrary(
            request: Aether_Empty,
            response: GRPCCore.RPCWriter<Aether_Game>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "LaunchGame" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LAUNCHING: The core function
        ///
        /// - Parameters:
        ///   - request: A `Aether_LaunchRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_LaunchResponse` to respond with.
        func launchGame(
            request: Aether_LaunchRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_LaunchResponse

        /// Handle the "StopGame" method.
        ///
        /// - Parameters:
        ///   - request: A `Aether_GameId` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_OperationStatus` to respond with.
        func stopGame(
            request: Aether_GameId,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_OperationStatus

        /// Handle the "SubscribeToGameState" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
        ///
        /// - Parameters:
        ///   - request: A `Aether_Empty` message.
        ///   - response: A response stream of `Aether_GameStateUpdate` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func subscribeToGameState(
            request: Aether_Empty,
            response: GRPCCore.RPCWriter<Aether_GameStateUpdate>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "GetGameDetailWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PLUGINS: The interactive layer
        /// > Frontend asks: "What widgets should I show for this game?"
        ///
        /// - Parameters:
        ///   - request: A `Aether_GameId` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_WidgetList` to respond with.
        func getGameDetailWidgets(
            request: Aether_GameId,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_WidgetList

        /// Handle the "TriggerPluginAction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Frontend says: "User clicked the button in the plugin widget"
        ///
        /// - Parameters:
        ///   - request: A `Aether_PluginAction` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_OperationStatus` to respond with.
        func triggerPluginAction(
            request: Aether_PluginAction,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_OperationStatus

        /// Handle the "GetPlugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of loaded plugins
        ///
        /// - Parameters:
        ///   - request: A `Aether_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_PluginList` to respond with.
        func getPlugins(
            request: Aether_Empty,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_PluginList

        /// Handle the "GetSetupWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
        ///
        /// - Parameters:
        ///   - request: A `Aether_PluginName` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Aether_WidgetList` to respond with.
        func getSetupWidgets(
            request: Aether_PluginName,
            context: GRPCCore.ServerContext
        ) async throws -> Aether_WidgetList
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.ScanLibrary.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_ScanRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_ScanProgress>(),
            handler: { request, context in
                try await self.scanLibrary(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.GetLibrary.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_Game>(),
            handler: { request, context in
                try await self.getLibrary(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.LaunchGame.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_LaunchRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_LaunchResponse>(),
            handler: { request, context in
                try await self.launchGame(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.StopGame.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_GameId>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_OperationStatus>(),
            handler: { request, context in
                try await self.stopGame(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.SubscribeToGameState.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_GameStateUpdate>(),
            handler: { request, context in
                try await self.subscribeToGameState(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.GetGameDetailWidgets.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_GameId>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_WidgetList>(),
            handler: { request, context in
                try await self.getGameDetailWidgets(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.TriggerPluginAction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_PluginAction>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_OperationStatus>(),
            handler: { request, context in
                try await self.triggerPluginAction(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.GetPlugins.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_PluginList>(),
            handler: { request, context in
                try await self.getPlugins(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Aether_AetherOrchestrator.Method.GetSetupWidgets.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_PluginName>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_WidgetList>(),
            handler: { request, context in
                try await self.getSetupWidgets(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator.ServiceProtocol {
    internal func scanLibrary(
        request: GRPCCore.StreamingServerRequest<Aether_ScanRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_ScanProgress> {
        let response = try await self.scanLibrary(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    internal func getLibrary(
        request: GRPCCore.StreamingServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_Game> {
        let response = try await self.getLibrary(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    internal func launchGame(
        request: GRPCCore.StreamingServerRequest<Aether_LaunchRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_LaunchResponse> {
        let response = try await self.launchGame(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func stopGame(
        request: GRPCCore.StreamingServerRequest<Aether_GameId>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_OperationStatus> {
        let response = try await self.stopGame(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func subscribeToGameState(
        request: GRPCCore.StreamingServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_GameStateUpdate> {
        let response = try await self.subscribeToGameState(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    internal func getGameDetailWidgets(
        request: GRPCCore.StreamingServerRequest<Aether_GameId>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_WidgetList> {
        let response = try await self.getGameDetailWidgets(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func triggerPluginAction(
        request: GRPCCore.StreamingServerRequest<Aether_PluginAction>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_OperationStatus> {
        let response = try await self.triggerPluginAction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func getPlugins(
        request: GRPCCore.StreamingServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_PluginList> {
        let response = try await self.getPlugins(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func getSetupWidgets(
        request: GRPCCore.StreamingServerRequest<Aether_PluginName>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_WidgetList> {
        let response = try await self.getSetupWidgets(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator.SimpleServiceProtocol {
    internal func scanLibrary(
        request: GRPCCore.ServerRequest<Aether_ScanRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_ScanProgress> {
        return GRPCCore.StreamingServerResponse<Aether_ScanProgress>(
            metadata: [:],
            producer: { writer in
                try await self.scanLibrary(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    internal func getLibrary(
        request: GRPCCore.ServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_Game> {
        return GRPCCore.StreamingServerResponse<Aether_Game>(
            metadata: [:],
            producer: { writer in
                try await self.getLibrary(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    internal func launchGame(
        request: GRPCCore.ServerRequest<Aether_LaunchRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_LaunchResponse> {
        return GRPCCore.ServerResponse<Aether_LaunchResponse>(
            message: try await self.launchGame(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func stopGame(
        request: GRPCCore.ServerRequest<Aether_GameId>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_OperationStatus> {
        return GRPCCore.ServerResponse<Aether_OperationStatus>(
            message: try await self.stopGame(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func subscribeToGameState(
        request: GRPCCore.ServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Aether_GameStateUpdate> {
        return GRPCCore.StreamingServerResponse<Aether_GameStateUpdate>(
            metadata: [:],
            producer: { writer in
                try await self.subscribeToGameState(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    internal func getGameDetailWidgets(
        request: GRPCCore.ServerRequest<Aether_GameId>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_WidgetList> {
        return GRPCCore.ServerResponse<Aether_WidgetList>(
            message: try await self.getGameDetailWidgets(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func triggerPluginAction(
        request: GRPCCore.ServerRequest<Aether_PluginAction>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_OperationStatus> {
        return GRPCCore.ServerResponse<Aether_OperationStatus>(
            message: try await self.triggerPluginAction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func getPlugins(
        request: GRPCCore.ServerRequest<Aether_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_PluginList> {
        return GRPCCore.ServerResponse<Aether_PluginList>(
            message: try await self.getPlugins(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func getSetupWidgets(
        request: GRPCCore.ServerRequest<Aether_PluginName>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Aether_WidgetList> {
        return GRPCCore.ServerResponse<Aether_WidgetList>(
            message: try await self.getSetupWidgets(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: aether.AetherOrchestrator (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator {
    /// Generated client protocol for the "aether.AetherOrchestrator" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "ScanLibrary" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LIBRARY: Getting games into the UI
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_ScanRequest` message.
        ///   - serializer: A serializer for `Aether_ScanRequest` messages.
        ///   - deserializer: A deserializer for `Aether_ScanProgress` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func scanLibrary<Result>(
            request: GRPCCore.ClientRequest<Aether_ScanRequest>,
            serializer: some GRPCCore.MessageSerializer<Aether_ScanRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_ScanProgress>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_ScanProgress>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetLibrary" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_Game` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getLibrary<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_Game>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_Game>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "LaunchGame" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LAUNCHING: The core function
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_LaunchRequest` message.
        ///   - serializer: A serializer for `Aether_LaunchRequest` messages.
        ///   - deserializer: A deserializer for `Aether_LaunchResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func launchGame<Result>(
            request: GRPCCore.ClientRequest<Aether_LaunchRequest>,
            serializer: some GRPCCore.MessageSerializer<Aether_LaunchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_LaunchResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_LaunchResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "StopGame" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - serializer: A serializer for `Aether_GameId` messages.
        ///   - deserializer: A deserializer for `Aether_OperationStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func stopGame<Result>(
            request: GRPCCore.ClientRequest<Aether_GameId>,
            serializer: some GRPCCore.MessageSerializer<Aether_GameId>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_OperationStatus>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SubscribeToGameState" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_GameStateUpdate` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func subscribeToGameState<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_GameStateUpdate>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_GameStateUpdate>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetGameDetailWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PLUGINS: The interactive layer
        /// > Frontend asks: "What widgets should I show for this game?"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - serializer: A serializer for `Aether_GameId` messages.
        ///   - deserializer: A deserializer for `Aether_WidgetList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getGameDetailWidgets<Result>(
            request: GRPCCore.ClientRequest<Aether_GameId>,
            serializer: some GRPCCore.MessageSerializer<Aether_GameId>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_WidgetList>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TriggerPluginAction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Frontend says: "User clicked the button in the plugin widget"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginAction` message.
        ///   - serializer: A serializer for `Aether_PluginAction` messages.
        ///   - deserializer: A deserializer for `Aether_OperationStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func triggerPluginAction<Result>(
            request: GRPCCore.ClientRequest<Aether_PluginAction>,
            serializer: some GRPCCore.MessageSerializer<Aether_PluginAction>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_OperationStatus>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetPlugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of loaded plugins
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_PluginList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getPlugins<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_PluginList>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_PluginList>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetSetupWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginName` message.
        ///   - serializer: A serializer for `Aether_PluginName` messages.
        ///   - deserializer: A deserializer for `Aether_WidgetList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getSetupWidgets<Result>(
            request: GRPCCore.ClientRequest<Aether_PluginName>,
            serializer: some GRPCCore.MessageSerializer<Aether_PluginName>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_WidgetList>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "aether.AetherOrchestrator" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ScanLibrary" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LIBRARY: Getting games into the UI
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_ScanRequest` message.
        ///   - serializer: A serializer for `Aether_ScanRequest` messages.
        ///   - deserializer: A deserializer for `Aether_ScanProgress` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func scanLibrary<Result>(
            request: GRPCCore.ClientRequest<Aether_ScanRequest>,
            serializer: some GRPCCore.MessageSerializer<Aether_ScanRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_ScanProgress>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_ScanProgress>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.ScanLibrary.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetLibrary" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_Game` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getLibrary<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_Game>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_Game>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.GetLibrary.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "LaunchGame" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LAUNCHING: The core function
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_LaunchRequest` message.
        ///   - serializer: A serializer for `Aether_LaunchRequest` messages.
        ///   - deserializer: A deserializer for `Aether_LaunchResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func launchGame<Result>(
            request: GRPCCore.ClientRequest<Aether_LaunchRequest>,
            serializer: some GRPCCore.MessageSerializer<Aether_LaunchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_LaunchResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_LaunchResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.LaunchGame.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "StopGame" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - serializer: A serializer for `Aether_GameId` messages.
        ///   - deserializer: A deserializer for `Aether_OperationStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func stopGame<Result>(
            request: GRPCCore.ClientRequest<Aether_GameId>,
            serializer: some GRPCCore.MessageSerializer<Aether_GameId>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_OperationStatus>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.StopGame.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SubscribeToGameState" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_GameStateUpdate` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func subscribeToGameState<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_GameStateUpdate>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_GameStateUpdate>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.SubscribeToGameState.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetGameDetailWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PLUGINS: The interactive layer
        /// > Frontend asks: "What widgets should I show for this game?"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_GameId` message.
        ///   - serializer: A serializer for `Aether_GameId` messages.
        ///   - deserializer: A deserializer for `Aether_WidgetList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getGameDetailWidgets<Result>(
            request: GRPCCore.ClientRequest<Aether_GameId>,
            serializer: some GRPCCore.MessageSerializer<Aether_GameId>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_WidgetList>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.GetGameDetailWidgets.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TriggerPluginAction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Frontend says: "User clicked the button in the plugin widget"
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginAction` message.
        ///   - serializer: A serializer for `Aether_PluginAction` messages.
        ///   - deserializer: A deserializer for `Aether_OperationStatus` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func triggerPluginAction<Result>(
            request: GRPCCore.ClientRequest<Aether_PluginAction>,
            serializer: some GRPCCore.MessageSerializer<Aether_PluginAction>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_OperationStatus>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.TriggerPluginAction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetPlugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get list of loaded plugins
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_Empty` message.
        ///   - serializer: A serializer for `Aether_Empty` messages.
        ///   - deserializer: A deserializer for `Aether_PluginList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getPlugins<Result>(
            request: GRPCCore.ClientRequest<Aether_Empty>,
            serializer: some GRPCCore.MessageSerializer<Aether_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_PluginList>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_PluginList>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.GetPlugins.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetSetupWidgets" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Aether_PluginName` message.
        ///   - serializer: A serializer for `Aether_PluginName` messages.
        ///   - deserializer: A deserializer for `Aether_WidgetList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getSetupWidgets<Result>(
            request: GRPCCore.ClientRequest<Aether_PluginName>,
            serializer: some GRPCCore.MessageSerializer<Aether_PluginName>,
            deserializer: some GRPCCore.MessageDeserializer<Aether_WidgetList>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Aether_AetherOrchestrator.Method.GetSetupWidgets.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator.ClientProtocol {
    /// Call the "ScanLibrary" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LIBRARY: Getting games into the UI
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_ScanRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func scanLibrary<Result>(
        request: GRPCCore.ClientRequest<Aether_ScanRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_ScanProgress>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.scanLibrary(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_ScanRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_ScanProgress>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLibrary" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getLibrary<Result>(
        request: GRPCCore.ClientRequest<Aether_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_Game>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.getLibrary(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_Game>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LaunchGame" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LAUNCHING: The core function
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_LaunchRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func launchGame<Result>(
        request: GRPCCore.ClientRequest<Aether_LaunchRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_LaunchResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.launchGame(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_LaunchRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_LaunchResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StopGame" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_GameId` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func stopGame<Result>(
        request: GRPCCore.ClientRequest<Aether_GameId>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.stopGame(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_GameId>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_OperationStatus>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubscribeToGameState" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func subscribeToGameState<Result>(
        request: GRPCCore.ClientRequest<Aether_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_GameStateUpdate>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.subscribeToGameState(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_GameStateUpdate>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetGameDetailWidgets" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PLUGINS: The interactive layer
    /// > Frontend asks: "What widgets should I show for this game?"
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_GameId` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getGameDetailWidgets<Result>(
        request: GRPCCore.ClientRequest<Aether_GameId>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getGameDetailWidgets(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_GameId>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_WidgetList>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TriggerPluginAction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Frontend says: "User clicked the button in the plugin widget"
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_PluginAction` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func triggerPluginAction<Result>(
        request: GRPCCore.ClientRequest<Aether_PluginAction>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.triggerPluginAction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_PluginAction>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_OperationStatus>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetPlugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of loaded plugins
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getPlugins<Result>(
        request: GRPCCore.ClientRequest<Aether_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_PluginList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getPlugins(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_PluginList>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSetupWidgets" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Aether_PluginName` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getSetupWidgets<Result>(
        request: GRPCCore.ClientRequest<Aether_PluginName>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getSetupWidgets(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Aether_PluginName>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Aether_WidgetList>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Aether_AetherOrchestrator.ClientProtocol {
    /// Call the "ScanLibrary" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LIBRARY: Getting games into the UI
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func scanLibrary<Result>(
        _ message: Aether_ScanRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_ScanProgress>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_ScanRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.scanLibrary(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLibrary" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getLibrary<Result>(
        _ message: Aether_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_Game>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.getLibrary(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LaunchGame" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LAUNCHING: The core function
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func launchGame<Result>(
        _ message: Aether_LaunchRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_LaunchResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_LaunchRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.launchGame(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StopGame" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func stopGame<Result>(
        _ message: Aether_GameId,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_GameId>(
            message: message,
            metadata: metadata
        )
        return try await self.stopGame(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubscribeToGameState" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Streams updates (e.g., "Running", "Stopping") so the UI Play button changes color
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func subscribeToGameState<Result>(
        _ message: Aether_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Aether_GameStateUpdate>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.subscribeToGameState(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetGameDetailWidgets" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PLUGINS: The interactive layer
    /// > Frontend asks: "What widgets should I show for this game?"
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getGameDetailWidgets<Result>(
        _ message: Aether_GameId,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_GameId>(
            message: message,
            metadata: metadata
        )
        return try await self.getGameDetailWidgets(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TriggerPluginAction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Frontend says: "User clicked the button in the plugin widget"
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func triggerPluginAction<Result>(
        _ message: Aether_PluginAction,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_OperationStatus>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_PluginAction>(
            message: message,
            metadata: metadata
        )
        return try await self.triggerPluginAction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetPlugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get list of loaded plugins
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getPlugins<Result>(
        _ message: Aether_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_PluginList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.getPlugins(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSetupWidgets" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server-Driven UI for Plugin Setup (e.g., "Add Game" for Custom Importer)
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getSetupWidgets<Result>(
        _ message: Aether_PluginName,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Aether_WidgetList>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Aether_PluginName>(
            message: message,
            metadata: metadata
        )
        return try await self.getSetupWidgets(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}