// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aether.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Aether_Platform: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknown // = 0
  case steam // = 1
  case epic // = 2
  case gog // = 3
  case local // = 4
  case battleNet // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .steam
    case 2: self = .epic
    case 3: self = .gog
    case 4: self = .local
    case 5: self = .battleNet
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .steam: return 1
    case .epic: return 2
    case .gog: return 3
    case .local: return 4
    case .battleNet: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Aether_Platform] = [
    .unknown,
    .steam,
    .epic,
    .gog,
    .local,
    .battleNet,
  ]

}

struct Aether_Empty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_Game: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var title: String {
    get {return _storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var platform: String {
    get {return _storage._platform}
    set {_uniqueStorage()._platform = newValue}
  }

  var externalID: String {
    get {return _storage._externalID}
    set {_uniqueStorage()._externalID = newValue}
  }

  var installPath: String {
    get {return _storage._installPath}
    set {_uniqueStorage()._installPath = newValue}
  }

  var executablePath: String {
    get {return _storage._executablePath}
    set {_uniqueStorage()._executablePath = newValue}
  }

  /// Images & Media
  var coverImageURL: String {
    get {return _storage._coverImageURL}
    set {_uniqueStorage()._coverImageURL = newValue}
  }

  var backgroundImageURL: String {
    get {return _storage._backgroundImageURL}
    set {_uniqueStorage()._backgroundImageURL = newValue}
  }

  var logoImageURL: String {
    get {return _storage._logoImageURL}
    set {_uniqueStorage()._logoImageURL = newValue}
  }

  var screenshots: [String] {
    get {return _storage._screenshots}
    set {_uniqueStorage()._screenshots = newValue}
  }

  var videos: [String] {
    get {return _storage._videos}
    set {_uniqueStorage()._videos = newValue}
  }

  /// Description & Classification
  var description_p: String {
    get {return _storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  var shortDescription: String {
    get {return _storage._shortDescription}
    set {_uniqueStorage()._shortDescription = newValue}
  }

  var genres: [String] {
    get {return _storage._genres}
    set {_uniqueStorage()._genres = newValue}
  }

  var tags: [String] {
    get {return _storage._tags}
    set {_uniqueStorage()._tags = newValue}
  }

  var categories: [String] {
    get {return _storage._categories}
    set {_uniqueStorage()._categories = newValue}
  }

  /// People & Dates
  var developer: String {
    get {return _storage._developer}
    set {_uniqueStorage()._developer = newValue}
  }

  var publisher: String {
    get {return _storage._publisher}
    set {_uniqueStorage()._publisher = newValue}
  }

  /// Unix timestamp
  var releaseDateUnix: Int64 {
    get {return _storage._releaseDateUnix}
    set {_uniqueStorage()._releaseDateUnix = newValue}
  }

  /// Ratings & Reviews
  var metacriticScore: Double {
    get {return _storage._metacriticScore}
    set {_uniqueStorage()._metacriticScore = newValue}
  }

  var userScore: Double {
    get {return _storage._userScore}
    set {_uniqueStorage()._userScore = newValue}
  }

  var reviewCount: Int32 {
    get {return _storage._reviewCount}
    set {_uniqueStorage()._reviewCount = newValue}
  }

  /// Features
  var hasAchievements_p: Bool {
    get {return _storage._hasAchievements_p}
    set {_uniqueStorage()._hasAchievements_p = newValue}
  }

  var achievementCount: Int32 {
    get {return _storage._achievementCount}
    set {_uniqueStorage()._achievementCount = newValue}
  }

  var hasMultiplayer_p: Bool {
    get {return _storage._hasMultiplayer_p}
    set {_uniqueStorage()._hasMultiplayer_p = newValue}
  }

  var hasSinglePlayer_p: Bool {
    get {return _storage._hasSinglePlayer_p}
    set {_uniqueStorage()._hasSinglePlayer_p = newValue}
  }

  var hasCloudSaves_p: Bool {
    get {return _storage._hasCloudSaves_p}
    set {_uniqueStorage()._hasCloudSaves_p = newValue}
  }

  /// System Requirements
  var minimumRequirements: String {
    get {return _storage._minimumRequirements}
    set {_uniqueStorage()._minimumRequirements = newValue}
  }

  var recommendedRequirements: String {
    get {return _storage._recommendedRequirements}
    set {_uniqueStorage()._recommendedRequirements = newValue}
  }

  var supportedLanguages: [String] {
    get {return _storage._supportedLanguages}
    set {_uniqueStorage()._supportedLanguages = newValue}
  }

  /// User Stats
  var lastPlayedUnix: Int64 {
    get {return _storage._lastPlayedUnix}
    set {_uniqueStorage()._lastPlayedUnix = newValue}
  }

  var totalPlaytimeSeconds: Int64 {
    get {return _storage._totalPlaytimeSeconds}
    set {_uniqueStorage()._totalPlaytimeSeconds = newValue}
  }

  var isFavorite: Bool {
    get {return _storage._isFavorite}
    set {_uniqueStorage()._isFavorite = newValue}
  }

  var isInstalled: Bool {
    get {return _storage._isInstalled}
    set {_uniqueStorage()._isInstalled = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Aether_GameId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_LaunchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var gameID: String = String()

  var runAsAdmin: Bool = false

  /// E.g., for Mac: "Use Game Porting Toolkit"
  var launchArguments: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_LaunchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var errorMessage: String = String()

  var processID: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_GameStateUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var gameID: String = String()

  var newState: Aether_GameStateUpdate.State = .stopped

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case stopped // = 0
    case launching // = 1
    case running // = 2
    case suspended // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .stopped
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .stopped
      case 1: self = .launching
      case 2: self = .running
      case 3: self = .suspended
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .stopped: return 0
      case .launching: return 1
      case .running: return 2
      case .suspended: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Aether_GameStateUpdate.State] = [
      .stopped,
      .launching,
      .running,
      .suspended,
    ]

  }

  init() {}
}

struct Aether_WidgetList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var widgets: [Aether_PluginWidget] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The "Adaptive Card" JSON. 
/// The backend defines the layout, Frontend just renders it.
struct Aether_PluginWidget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pluginID: String = String()

  var title: String = String()

  /// JSON string defining layout (e.g., { "type": "Button", "label": "Sync Saves" })
  var layoutJson: String = String()

  var sortOrder: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_PluginAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pluginName: String = String()

  /// e.g., "SYNC_BUTTON_CLICKED"
  var actionID: String = String()

  var gameID: String = String()

  /// Any extra data needed
  var payloadJson: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_PluginList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var plugins: [Aether_PluginInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_PluginInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var version: String = String()

  var author: String = String()

  var isImporter: Bool = false

  var isMetadataProvider: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_PluginName: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_OperationStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_ScanRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forceRefresh: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Aether_ScanProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var currentPlatform: String = String()

  var gamesFound: Int32 = 0

  var gamesProcessed: Int32 = 0

  var currentGame: String = String()

  var progressPercentage: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "aether"

extension Aether_Platform: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0\u{1}STEAM\0\u{1}EPIC\0\u{1}GOG\0\u{1}LOCAL\0\u{1}BATTLE_NET\0")
}

extension Aether_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Empty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_Empty, rhs: Aether_Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_Game: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Game"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}title\0\u{1}platform\0\u{3}external_id\0\u{3}install_path\0\u{3}executable_path\0\u{3}cover_image_url\0\u{3}background_image_url\0\u{3}logo_image_url\0\u{1}screenshots\0\u{1}videos\0\u{1}description\0\u{3}short_description\0\u{1}genres\0\u{1}tags\0\u{1}categories\0\u{1}developer\0\u{1}publisher\0\u{3}release_date_unix\0\u{3}metacritic_score\0\u{3}user_score\0\u{3}review_count\0\u{3}has_achievements\0\u{3}achievement_count\0\u{3}has_multiplayer\0\u{3}has_single_player\0\u{3}has_cloud_saves\0\u{3}minimum_requirements\0\u{3}recommended_requirements\0\u{3}supported_languages\0\u{3}last_played_unix\0\u{3}total_playtime_seconds\0\u{3}is_favorite\0\u{3}is_installed\0")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _title: String = String()
    var _platform: String = String()
    var _externalID: String = String()
    var _installPath: String = String()
    var _executablePath: String = String()
    var _coverImageURL: String = String()
    var _backgroundImageURL: String = String()
    var _logoImageURL: String = String()
    var _screenshots: [String] = []
    var _videos: [String] = []
    var _description_p: String = String()
    var _shortDescription: String = String()
    var _genres: [String] = []
    var _tags: [String] = []
    var _categories: [String] = []
    var _developer: String = String()
    var _publisher: String = String()
    var _releaseDateUnix: Int64 = 0
    var _metacriticScore: Double = 0
    var _userScore: Double = 0
    var _reviewCount: Int32 = 0
    var _hasAchievements_p: Bool = false
    var _achievementCount: Int32 = 0
    var _hasMultiplayer_p: Bool = false
    var _hasSinglePlayer_p: Bool = false
    var _hasCloudSaves_p: Bool = false
    var _minimumRequirements: String = String()
    var _recommendedRequirements: String = String()
    var _supportedLanguages: [String] = []
    var _lastPlayedUnix: Int64 = 0
    var _totalPlaytimeSeconds: Int64 = 0
    var _isFavorite: Bool = false
    var _isInstalled: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _title = source._title
      _platform = source._platform
      _externalID = source._externalID
      _installPath = source._installPath
      _executablePath = source._executablePath
      _coverImageURL = source._coverImageURL
      _backgroundImageURL = source._backgroundImageURL
      _logoImageURL = source._logoImageURL
      _screenshots = source._screenshots
      _videos = source._videos
      _description_p = source._description_p
      _shortDescription = source._shortDescription
      _genres = source._genres
      _tags = source._tags
      _categories = source._categories
      _developer = source._developer
      _publisher = source._publisher
      _releaseDateUnix = source._releaseDateUnix
      _metacriticScore = source._metacriticScore
      _userScore = source._userScore
      _reviewCount = source._reviewCount
      _hasAchievements_p = source._hasAchievements_p
      _achievementCount = source._achievementCount
      _hasMultiplayer_p = source._hasMultiplayer_p
      _hasSinglePlayer_p = source._hasSinglePlayer_p
      _hasCloudSaves_p = source._hasCloudSaves_p
      _minimumRequirements = source._minimumRequirements
      _recommendedRequirements = source._recommendedRequirements
      _supportedLanguages = source._supportedLanguages
      _lastPlayedUnix = source._lastPlayedUnix
      _totalPlaytimeSeconds = source._totalPlaytimeSeconds
      _isFavorite = source._isFavorite
      _isInstalled = source._isInstalled
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._platform) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._externalID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._installPath) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._executablePath) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._coverImageURL) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._backgroundImageURL) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._logoImageURL) }()
        case 10: try { try decoder.decodeRepeatedStringField(value: &_storage._screenshots) }()
        case 11: try { try decoder.decodeRepeatedStringField(value: &_storage._videos) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._shortDescription) }()
        case 14: try { try decoder.decodeRepeatedStringField(value: &_storage._genres) }()
        case 15: try { try decoder.decodeRepeatedStringField(value: &_storage._tags) }()
        case 16: try { try decoder.decodeRepeatedStringField(value: &_storage._categories) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._developer) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._publisher) }()
        case 19: try { try decoder.decodeSingularInt64Field(value: &_storage._releaseDateUnix) }()
        case 20: try { try decoder.decodeSingularDoubleField(value: &_storage._metacriticScore) }()
        case 21: try { try decoder.decodeSingularDoubleField(value: &_storage._userScore) }()
        case 22: try { try decoder.decodeSingularInt32Field(value: &_storage._reviewCount) }()
        case 23: try { try decoder.decodeSingularBoolField(value: &_storage._hasAchievements_p) }()
        case 24: try { try decoder.decodeSingularInt32Field(value: &_storage._achievementCount) }()
        case 25: try { try decoder.decodeSingularBoolField(value: &_storage._hasMultiplayer_p) }()
        case 26: try { try decoder.decodeSingularBoolField(value: &_storage._hasSinglePlayer_p) }()
        case 27: try { try decoder.decodeSingularBoolField(value: &_storage._hasCloudSaves_p) }()
        case 28: try { try decoder.decodeSingularStringField(value: &_storage._minimumRequirements) }()
        case 29: try { try decoder.decodeSingularStringField(value: &_storage._recommendedRequirements) }()
        case 30: try { try decoder.decodeRepeatedStringField(value: &_storage._supportedLanguages) }()
        case 31: try { try decoder.decodeSingularInt64Field(value: &_storage._lastPlayedUnix) }()
        case 32: try { try decoder.decodeSingularInt64Field(value: &_storage._totalPlaytimeSeconds) }()
        case 33: try { try decoder.decodeSingularBoolField(value: &_storage._isFavorite) }()
        case 34: try { try decoder.decodeSingularBoolField(value: &_storage._isInstalled) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 2)
      }
      if !_storage._platform.isEmpty {
        try visitor.visitSingularStringField(value: _storage._platform, fieldNumber: 3)
      }
      if !_storage._externalID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._externalID, fieldNumber: 4)
      }
      if !_storage._installPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._installPath, fieldNumber: 5)
      }
      if !_storage._executablePath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._executablePath, fieldNumber: 6)
      }
      if !_storage._coverImageURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._coverImageURL, fieldNumber: 7)
      }
      if !_storage._backgroundImageURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._backgroundImageURL, fieldNumber: 8)
      }
      if !_storage._logoImageURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._logoImageURL, fieldNumber: 9)
      }
      if !_storage._screenshots.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._screenshots, fieldNumber: 10)
      }
      if !_storage._videos.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._videos, fieldNumber: 11)
      }
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 12)
      }
      if !_storage._shortDescription.isEmpty {
        try visitor.visitSingularStringField(value: _storage._shortDescription, fieldNumber: 13)
      }
      if !_storage._genres.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._genres, fieldNumber: 14)
      }
      if !_storage._tags.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._tags, fieldNumber: 15)
      }
      if !_storage._categories.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._categories, fieldNumber: 16)
      }
      if !_storage._developer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._developer, fieldNumber: 17)
      }
      if !_storage._publisher.isEmpty {
        try visitor.visitSingularStringField(value: _storage._publisher, fieldNumber: 18)
      }
      if _storage._releaseDateUnix != 0 {
        try visitor.visitSingularInt64Field(value: _storage._releaseDateUnix, fieldNumber: 19)
      }
      if _storage._metacriticScore.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._metacriticScore, fieldNumber: 20)
      }
      if _storage._userScore.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._userScore, fieldNumber: 21)
      }
      if _storage._reviewCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._reviewCount, fieldNumber: 22)
      }
      if _storage._hasAchievements_p != false {
        try visitor.visitSingularBoolField(value: _storage._hasAchievements_p, fieldNumber: 23)
      }
      if _storage._achievementCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._achievementCount, fieldNumber: 24)
      }
      if _storage._hasMultiplayer_p != false {
        try visitor.visitSingularBoolField(value: _storage._hasMultiplayer_p, fieldNumber: 25)
      }
      if _storage._hasSinglePlayer_p != false {
        try visitor.visitSingularBoolField(value: _storage._hasSinglePlayer_p, fieldNumber: 26)
      }
      if _storage._hasCloudSaves_p != false {
        try visitor.visitSingularBoolField(value: _storage._hasCloudSaves_p, fieldNumber: 27)
      }
      if !_storage._minimumRequirements.isEmpty {
        try visitor.visitSingularStringField(value: _storage._minimumRequirements, fieldNumber: 28)
      }
      if !_storage._recommendedRequirements.isEmpty {
        try visitor.visitSingularStringField(value: _storage._recommendedRequirements, fieldNumber: 29)
      }
      if !_storage._supportedLanguages.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._supportedLanguages, fieldNumber: 30)
      }
      if _storage._lastPlayedUnix != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lastPlayedUnix, fieldNumber: 31)
      }
      if _storage._totalPlaytimeSeconds != 0 {
        try visitor.visitSingularInt64Field(value: _storage._totalPlaytimeSeconds, fieldNumber: 32)
      }
      if _storage._isFavorite != false {
        try visitor.visitSingularBoolField(value: _storage._isFavorite, fieldNumber: 33)
      }
      if _storage._isInstalled != false {
        try visitor.visitSingularBoolField(value: _storage._isInstalled, fieldNumber: 34)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_Game, rhs: Aether_Game) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._platform != rhs_storage._platform {return false}
        if _storage._externalID != rhs_storage._externalID {return false}
        if _storage._installPath != rhs_storage._installPath {return false}
        if _storage._executablePath != rhs_storage._executablePath {return false}
        if _storage._coverImageURL != rhs_storage._coverImageURL {return false}
        if _storage._backgroundImageURL != rhs_storage._backgroundImageURL {return false}
        if _storage._logoImageURL != rhs_storage._logoImageURL {return false}
        if _storage._screenshots != rhs_storage._screenshots {return false}
        if _storage._videos != rhs_storage._videos {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._shortDescription != rhs_storage._shortDescription {return false}
        if _storage._genres != rhs_storage._genres {return false}
        if _storage._tags != rhs_storage._tags {return false}
        if _storage._categories != rhs_storage._categories {return false}
        if _storage._developer != rhs_storage._developer {return false}
        if _storage._publisher != rhs_storage._publisher {return false}
        if _storage._releaseDateUnix != rhs_storage._releaseDateUnix {return false}
        if _storage._metacriticScore != rhs_storage._metacriticScore {return false}
        if _storage._userScore != rhs_storage._userScore {return false}
        if _storage._reviewCount != rhs_storage._reviewCount {return false}
        if _storage._hasAchievements_p != rhs_storage._hasAchievements_p {return false}
        if _storage._achievementCount != rhs_storage._achievementCount {return false}
        if _storage._hasMultiplayer_p != rhs_storage._hasMultiplayer_p {return false}
        if _storage._hasSinglePlayer_p != rhs_storage._hasSinglePlayer_p {return false}
        if _storage._hasCloudSaves_p != rhs_storage._hasCloudSaves_p {return false}
        if _storage._minimumRequirements != rhs_storage._minimumRequirements {return false}
        if _storage._recommendedRequirements != rhs_storage._recommendedRequirements {return false}
        if _storage._supportedLanguages != rhs_storage._supportedLanguages {return false}
        if _storage._lastPlayedUnix != rhs_storage._lastPlayedUnix {return false}
        if _storage._totalPlaytimeSeconds != rhs_storage._totalPlaytimeSeconds {return false}
        if _storage._isFavorite != rhs_storage._isFavorite {return false}
        if _storage._isInstalled != rhs_storage._isInstalled {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_GameId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GameId"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_GameId, rhs: Aether_GameId) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_LaunchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LaunchRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}game_id\0\u{3}run_as_admin\0\u{3}launch_arguments\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.gameID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.runAsAdmin) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.launchArguments) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.gameID.isEmpty {
      try visitor.visitSingularStringField(value: self.gameID, fieldNumber: 1)
    }
    if self.runAsAdmin != false {
      try visitor.visitSingularBoolField(value: self.runAsAdmin, fieldNumber: 2)
    }
    if !self.launchArguments.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.launchArguments, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_LaunchRequest, rhs: Aether_LaunchRequest) -> Bool {
    if lhs.gameID != rhs.gameID {return false}
    if lhs.runAsAdmin != rhs.runAsAdmin {return false}
    if lhs.launchArguments != rhs.launchArguments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_LaunchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LaunchResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{3}error_message\0\u{3}process_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.processID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    if self.processID != 0 {
      try visitor.visitSingularInt32Field(value: self.processID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_LaunchResponse, rhs: Aether_LaunchResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.processID != rhs.processID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_GameStateUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GameStateUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}game_id\0\u{3}new_state\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.gameID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.newState) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.gameID.isEmpty {
      try visitor.visitSingularStringField(value: self.gameID, fieldNumber: 1)
    }
    if self.newState != .stopped {
      try visitor.visitSingularEnumField(value: self.newState, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_GameStateUpdate, rhs: Aether_GameStateUpdate) -> Bool {
    if lhs.gameID != rhs.gameID {return false}
    if lhs.newState != rhs.newState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_GameStateUpdate.State: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STOPPED\0\u{1}LAUNCHING\0\u{1}RUNNING\0\u{1}SUSPENDED\0")
}

extension Aether_WidgetList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WidgetList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}widgets\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.widgets) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.widgets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.widgets, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_WidgetList, rhs: Aether_WidgetList) -> Bool {
    if lhs.widgets != rhs.widgets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_PluginWidget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PluginWidget"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}plugin_id\0\u{1}title\0\u{3}layout_json\0\u{3}sort_order\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pluginID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.layoutJson) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.sortOrder) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pluginID.isEmpty {
      try visitor.visitSingularStringField(value: self.pluginID, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.layoutJson.isEmpty {
      try visitor.visitSingularStringField(value: self.layoutJson, fieldNumber: 3)
    }
    if self.sortOrder != 0 {
      try visitor.visitSingularInt32Field(value: self.sortOrder, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_PluginWidget, rhs: Aether_PluginWidget) -> Bool {
    if lhs.pluginID != rhs.pluginID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.layoutJson != rhs.layoutJson {return false}
    if lhs.sortOrder != rhs.sortOrder {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_PluginAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PluginAction"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pluginName\0\u{1}actionId\0\u{1}gameId\0\u{3}payload_json\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pluginName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.actionID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.gameID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.payloadJson) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pluginName.isEmpty {
      try visitor.visitSingularStringField(value: self.pluginName, fieldNumber: 1)
    }
    if !self.actionID.isEmpty {
      try visitor.visitSingularStringField(value: self.actionID, fieldNumber: 2)
    }
    if !self.gameID.isEmpty {
      try visitor.visitSingularStringField(value: self.gameID, fieldNumber: 3)
    }
    if !self.payloadJson.isEmpty {
      try visitor.visitSingularStringField(value: self.payloadJson, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_PluginAction, rhs: Aether_PluginAction) -> Bool {
    if lhs.pluginName != rhs.pluginName {return false}
    if lhs.actionID != rhs.actionID {return false}
    if lhs.gameID != rhs.gameID {return false}
    if lhs.payloadJson != rhs.payloadJson {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_PluginList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PluginList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}plugins\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.plugins) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.plugins.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.plugins, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_PluginList, rhs: Aether_PluginList) -> Bool {
    if lhs.plugins != rhs.plugins {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_PluginInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PluginInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{1}author\0\u{1}isImporter\0\u{1}isMetadataProvider\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isImporter) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isMetadataProvider) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 3)
    }
    if self.isImporter != false {
      try visitor.visitSingularBoolField(value: self.isImporter, fieldNumber: 4)
    }
    if self.isMetadataProvider != false {
      try visitor.visitSingularBoolField(value: self.isMetadataProvider, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_PluginInfo, rhs: Aether_PluginInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.author != rhs.author {return false}
    if lhs.isImporter != rhs.isImporter {return false}
    if lhs.isMetadataProvider != rhs.isMetadataProvider {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_PluginName: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PluginName"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_PluginName, rhs: Aether_PluginName) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_OperationStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OperationStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_OperationStatus, rhs: Aether_OperationStatus) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_ScanRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ScanRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}force_refresh\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.forceRefresh) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.forceRefresh != false {
      try visitor.visitSingularBoolField(value: self.forceRefresh, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_ScanRequest, rhs: Aether_ScanRequest) -> Bool {
    if lhs.forceRefresh != rhs.forceRefresh {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Aether_ScanProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ScanProgress"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}current_platform\0\u{3}games_found\0\u{3}games_processed\0\u{3}current_game\0\u{3}progress_percentage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.currentPlatform) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.gamesFound) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.gamesProcessed) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.currentGame) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.progressPercentage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.currentPlatform.isEmpty {
      try visitor.visitSingularStringField(value: self.currentPlatform, fieldNumber: 1)
    }
    if self.gamesFound != 0 {
      try visitor.visitSingularInt32Field(value: self.gamesFound, fieldNumber: 2)
    }
    if self.gamesProcessed != 0 {
      try visitor.visitSingularInt32Field(value: self.gamesProcessed, fieldNumber: 3)
    }
    if !self.currentGame.isEmpty {
      try visitor.visitSingularStringField(value: self.currentGame, fieldNumber: 4)
    }
    if self.progressPercentage.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.progressPercentage, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Aether_ScanProgress, rhs: Aether_ScanProgress) -> Bool {
    if lhs.currentPlatform != rhs.currentPlatform {return false}
    if lhs.gamesFound != rhs.gamesFound {return false}
    if lhs.gamesProcessed != rhs.gamesProcessed {return false}
    if lhs.currentGame != rhs.currentGame {return false}
    if lhs.progressPercentage != rhs.progressPercentage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
