// This file is required for SwiftPM to recognize this target as a Swift module.
// The actual code is generated by the GRPCProtobufGenerator plugin from Resources/aether.proto.

import Foundation

public struct AetherIPCModule {
    public static let version = "1.0.0"
}
